//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TableSize
    {
        public int Id { get; set; }
        public string Sheet { get; set; }
        public string MachineFrame { get; set; }
        public Nullable<decimal> NormalLength { get; set; }
        public Nullable<decimal> WithEdgeLength { get; set; }
        public Nullable<decimal> NormalWidth { get; set; }
        public Nullable<decimal> WithEdgeWidth { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string Remark { get; set; }
        public Nullable<int> BasicCategoryId { get; set; }
        public Nullable<int> OrderMaterialId { get; set; }
    }
}
