//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OutsourceInfo
    {
        public int Id { get; set; }
        public string OutsourceName { get; set; }
        public string ShortName { get; set; }
        public string CompanyCode { get; set; }
        public string Region { get; set; }
        public Nullable<int> ProvinceId { get; set; }
        public Nullable<int> CityId { get; set; }
        public string Address { get; set; }
        public Nullable<System.DateTime> JoinDate { get; set; }
        public string ERPHost { get; set; }
        public string Contacts { get; set; }
        public string Tel { get; set; }
        public string Provinces { get; set; }
        public string Cities { get; set; }
        public Nullable<int> State { get; set; }
        public Nullable<int> AddUserId { get; set; }
        public Nullable<System.DateTime> AddDate { get; set; }
        public string Remark { get; set; }
    }
}
