//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADInvoice
    {
        public int Id { get; set; }
        public Nullable<int> SubjectId { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public Nullable<decimal> InvoiceMoney { get; set; }
        public string InvoiceNumber { get; set; }
        public Nullable<System.DateTime> ExpectReceiveDate { get; set; }
        public Nullable<System.DateTime> RealReceiveDate { get; set; }
        public string Remark { get; set; }
    }
}
