//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CheckOrderResult
    {
        public int Id { get; set; }
        public Nullable<int> CheckOrderId { get; set; }
        public Nullable<int> PlanDetailId { get; set; }
        public Nullable<int> SubjectId { get; set; }
        public string SubjectName { get; set; }
        public string RegionId { get; set; }
        public string RegionNames { get; set; }
        public string ProvinceId { get; set; }
        public string ProvinceName { get; set; }
        public string CityId { get; set; }
        public string CityTier { get; set; }
        public string IsInstall { get; set; }
        public Nullable<int> PositionId { get; set; }
        public string PositionName { get; set; }
        public string Format { get; set; }
        public string MaterialSupport { get; set; }
        public string POSScale { get; set; }
        public string Gender { get; set; }
        public string ChooseImg { get; set; }
        public Nullable<int> BasicPositionCount { get; set; }
        public Nullable<int> OrderPositionCount { get; set; }
    }
}
