//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExtraOrderDetail
    {
        public int Id { get; set; }
        public Nullable<int> OrderType { get; set; }
        public Nullable<int> SubjectId { get; set; }
        public Nullable<int> ShopId { get; set; }
        public string ShopNo { get; set; }
        public string ShopName { get; set; }
        public string Region { get; set; }
        public string Province { get; set; }
        public string City { get; set; }
        public string Address { get; set; }
        public string MaterialSupport { get; set; }
        public string POSScale { get; set; }
        public string Sheet { get; set; }
        public string MachineFrame { get; set; }
        public string GraphicNo { get; set; }
        public string CornerType { get; set; }
        public string Gender { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> GraphicWidth { get; set; }
        public Nullable<decimal> GraphicLength { get; set; }
        public string GraphicMaterial { get; set; }
        public string ChooseImg { get; set; }
        public string PositionDescription { get; set; }
        public string Remark { get; set; }
        public Nullable<int> AddUserId { get; set; }
        public Nullable<System.DateTime> AddDate { get; set; }
        public Nullable<int> HandMakeSubjectId { get; set; }
        public Nullable<int> IsSubmit { get; set; }
        public Nullable<int> ApproveState { get; set; }
        public Nullable<System.DateTime> ApproveDate { get; set; }
        public Nullable<bool> IsValid { get; set; }
        public Nullable<decimal> Price { get; set; }
    }
}
