//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Material
    {
        public int Id { get; set; }
        public Nullable<int> BigTypeId { get; set; }
        public Nullable<int> SmallTypeId { get; set; }
        public Nullable<int> MaterialBrandId { get; set; }
        public Nullable<int> MaterialCategoryId { get; set; }
        public string Specification { get; set; }
        public string MaterialName { get; set; }
        public Nullable<decimal> Width { get; set; }
        public Nullable<decimal> Length { get; set; }
        public Nullable<decimal> Area { get; set; }
        public string Unit { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> AddDate { get; set; }
        public Nullable<bool> IsDelete { get; set; }
    }
}
