//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderChangeApplication
    {
        public int Id { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<int> SubjectGuidanceId { get; set; }
        public int AddUserId { get; set; }
        public Nullable<System.DateTime> AddDate { get; set; }
        public Nullable<int> ManagerApperoveState { get; set; }
        public Nullable<System.DateTime> ManagerApperoveDate { get; set; }
        public Nullable<int> ManagerApperoveUID { get; set; }
        public Nullable<int> FinancialApproveState { get; set; }
        public Nullable<int> FinancialApproveUID { get; set; }
        public Nullable<System.DateTime> FinancialApproveDate { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
        public Nullable<int> DeleteUserId { get; set; }
    }
}
