//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderMaterialBaseInfo
    {
        public int Id { get; set; }
        public string MaterailName { get; set; }
        public Nullable<decimal> MaterialLength { get; set; }
        public Nullable<decimal> MaterialWidth { get; set; }
        public Nullable<decimal> MaterialHigh { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<decimal> PayUnitPrice { get; set; }
        public string Remark { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<System.DateTime> AddDate { get; set; }
    }
}
