//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OutsourceOrderAssignConfig
    {
        public int Id { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<int> ConfigTypeId { get; set; }
        public string MaterialName { get; set; }
        public Nullable<int> ProductOutsourctId { get; set; }
        public Nullable<int> AssignType { get; set; }
        public string Channel { get; set; }
        public string Format { get; set; }
        public Nullable<int> Region { get; set; }
        public string ProvinceId { get; set; }
        public string CityId { get; set; }
        public Nullable<System.DateTime> AddDate { get; set; }
        public Nullable<bool> IsFullMatch { get; set; }
    }
}
