//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PropOrderDetail
    {
        public int Id { get; set; }
        public Nullable<int> OrderType { get; set; }
        public Nullable<int> GuidanceId { get; set; }
        public Nullable<int> SubjectId { get; set; }
        public string PropChannel { get; set; }
        public Nullable<int> ShopId { get; set; }
        public string ShopName { get; set; }
        public string ShopNo { get; set; }
        public string Region { get; set; }
        public string Province { get; set; }
        public string City { get; set; }
        public string Address { get; set; }
        public string Contact { get; set; }
        public string Tel { get; set; }
        public string MaterialName { get; set; }
        public string Sheet { get; set; }
        public string MaterialType { get; set; }
        public string Dimension { get; set; }
        public string ServiceType { get; set; }
        public string Packaging { get; set; }
        public Nullable<decimal> BOMCost { get; set; }
        public Nullable<decimal> ProcessingCost { get; set; }
        public Nullable<decimal> PackingCost { get; set; }
        public Nullable<decimal> TransportationCost { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public string UnitName { get; set; }
        public string Remark { get; set; }
        public Nullable<int> AddUserId { get; set; }
        public Nullable<System.DateTime> AddDate { get; set; }
        public Nullable<bool> IsDelete { get; set; }
    }
}
