//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuoteDifferenceDetail
    {
        public int Id { get; set; }
        public Nullable<int> QuoteItemId { get; set; }
        public string Sheet { get; set; }
        public Nullable<int> OrderType { get; set; }
        public string MaterialName { get; set; }
        public Nullable<decimal> MaterialUnitPrice { get; set; }
        public Nullable<decimal> AddArea { get; set; }
        public Nullable<int> InstallUnitPrice { get; set; }
        public string AddPriceType { get; set; }
        public Nullable<decimal> AddPrice { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> AddDate { get; set; }
        public Nullable<int> AddUserId { get; set; }
    }
}
