//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shop
    {
        public int Id { get; set; }
        public string ShopName { get; set; }
        public string ShopNo { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<int> RegionId { get; set; }
        public string RegionName { get; set; }
        public Nullable<int> ProvinceId { get; set; }
        public string ProvinceName { get; set; }
        public Nullable<int> CityId { get; set; }
        public string CityName { get; set; }
        public Nullable<int> AreaId { get; set; }
        public string AreaName { get; set; }
        public string CityTier { get; set; }
        public string IsInstall { get; set; }
        public string InstallLevel { get; set; }
        public string AgentCode { get; set; }
        public string AgentName { get; set; }
        public string POPAddress { get; set; }
        public string Contact1 { get; set; }
        public string Tel1 { get; set; }
        public string Contact2 { get; set; }
        public string Tel2 { get; set; }
        public string Channel { get; set; }
        public string Format { get; set; }
        public string ShopLevel { get; set; }
        public string LocationType { get; set; }
        public string BusinessModel { get; set; }
        public Nullable<System.DateTime> OpeningDate { get; set; }
        public string Status { get; set; }
        public string MaterialSupport { get; set; }
        public string POSScale { get; set; }
        public string Remark { get; set; }
        public Nullable<int> AddUserId { get; set; }
        public Nullable<System.DateTime> AddDate { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<int> CSUserId { get; set; }
        public Nullable<int> IsInvalid { get; set; }
        public Nullable<decimal> InstallPrice { get; set; }
        public Nullable<decimal> Freight { get; set; }
        public Nullable<decimal> WindowInstallPrice { get; set; }
        public Nullable<decimal> BasicInstallPrice { get; set; }
        public string Category { get; set; }
        public string ShopType { get; set; }
        public Nullable<decimal> BCSInstallPrice { get; set; }
        public Nullable<decimal> OutsourceInstallPrice { get; set; }
        public Nullable<decimal> OutsourceBCSInstallPrice { get; set; }
        public Nullable<int> OutsourceId { get; set; }
        public string BCSIsInstall { get; set; }
        public Nullable<int> OOHInstallOutsourceId { get; set; }
        public Nullable<int> BCSOutsourceId { get; set; }
        public Nullable<int> ProductOutsourceId { get; set; }
    }
}
