//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShopMachineFrameChangeDetail
    {
        public int Id { get; set; }
        public Nullable<int> LogId { get; set; }
        public Nullable<int> ShopId { get; set; }
        public string PositionName { get; set; }
        public string MachineFrame { get; set; }
        public string Gender { get; set; }
        public Nullable<int> Count { get; set; }
        public string CornerType { get; set; }
        public Nullable<int> LevelNum { get; set; }
        public string Remark { get; set; }
        public Nullable<bool> IsValid { get; set; }
        public Nullable<int> AddUserId { get; set; }
        public Nullable<System.DateTime> AddDate { get; set; }
    }
}
