//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SplitOrderPlanDetail
    {
        public int Id { get; set; }
        public Nullable<int> PlanId { get; set; }
        public Nullable<int> OrderType { get; set; }
        public Nullable<decimal> GraphicWidth { get; set; }
        public Nullable<decimal> GraphicLength { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string GraphicMaterial { get; set; }
        public string Supplier { get; set; }
        public Nullable<decimal> RackSalePrice { get; set; }
        public string Remark { get; set; }
        public Nullable<int> AddUserId { get; set; }
        public Nullable<System.DateTime> AddDate { get; set; }
        public Nullable<int> CustomerMaterialId { get; set; }
        public string NewChooseImg { get; set; }
        public Nullable<bool> IsInSet { get; set; }
        public Nullable<bool> IsPerShop { get; set; }
        public string NewGender { get; set; }
        public Nullable<bool> IsHCPOP { get; set; }
        public Nullable<bool> LeftSideStick { get; set; }
        public Nullable<bool> RightSideStick { get; set; }
        public Nullable<bool> Floor { get; set; }
        public Nullable<bool> WindowStick { get; set; }
        public string WindowType { get; set; }
    }
}
