//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subject
    {
        public int Id { get; set; }
        public Nullable<int> SubjectType { get; set; }
        public string SubjectName { get; set; }
        public string OutSubjectName { get; set; }
        public string SubjectNo { get; set; }
        public Nullable<int> AddOrderType { get; set; }
        public string Contact { get; set; }
        public string Tel { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<System.DateTime> BeginDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> AddUserId { get; set; }
        public Nullable<System.DateTime> AddDate { get; set; }
        public Nullable<int> Status { get; set; }
        public string Remark { get; set; }
        public Nullable<int> ApproveState { get; set; }
        public Nullable<int> ApproveUserId { get; set; }
        public Nullable<System.DateTime> ApproveDate { get; set; }
        public string ApproveRemark { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public string SplitPlanIds { get; set; }
        public Nullable<decimal> SaleCost { get; set; }
        public Nullable<decimal> PredictCost { get; set; }
        public Nullable<int> GuidanceId { get; set; }
        public Nullable<int> ActivityId { get; set; }
        public Nullable<int> SubjectTypeId { get; set; }
        public Nullable<int> IsHandMade { get; set; }
        public Nullable<int> IsInstall { get; set; }
        public Nullable<int> SubjectCategoryId { get; set; }
        public Nullable<int> HandMakeSubjectId { get; set; }
        public Nullable<bool> HasHC { get; set; }
        public Nullable<decimal> SecondInstallPrice { get; set; }
        public string Region { get; set; }
        public string SupplementRegion { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
        public Nullable<int> RegionOrderType { get; set; }
        public Nullable<int> SubmitUserId { get; set; }
        public string PriceBlongRegion { get; set; }
        public string CornerType { get; set; }
        public Nullable<bool> IsRead { get; set; }
        public Nullable<int> OutsourceId { get; set; }
        public Nullable<bool> IsSecondInstall { get; set; }
        public Nullable<int> SecondBasicInstallPriceType { get; set; }
    }
}
