//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubjectLog
    {
        public int Id { get; set; }
        public Nullable<int> SubjectId { get; set; }
        public Nullable<int> SubjectType { get; set; }
        public string OperateType { get; set; }
        public Nullable<int> OperateUserId { get; set; }
        public Nullable<System.DateTime> OperateDate { get; set; }
        public string ApproveMsg { get; set; }
    }
}
