//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubjectGuidance
    {
        public int ItemId { get; set; }
        public Nullable<int> AddType { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<int> PriceItemId { get; set; }
        public string ItemName { get; set; }
        public Nullable<int> ActivityTypeId { get; set; }
        public Nullable<System.DateTime> BeginDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string SubjectNames { get; set; }
        public string Remark { get; set; }
        public Nullable<int> AddUserId { get; set; }
        public Nullable<System.DateTime> AddDate { get; set; }
        public Nullable<int> ProductApproveState { get; set; }
        public Nullable<int> ProductApproveUserId { get; set; }
        public Nullable<System.DateTime> ProductApproveDate { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
        public Nullable<int> DeleteUserId { get; set; }
        public Nullable<bool> IsFinish { get; set; }
        public Nullable<System.DateTime> FinishDate { get; set; }
        public Nullable<int> FinishUserId { get; set; }
        public Nullable<int> AccountStatus { get; set; }
        public Nullable<decimal> AccountAmount { get; set; }
        public Nullable<System.DateTime> AccountDate { get; set; }
        public Nullable<int> AccountUserId { get; set; }
        public Nullable<int> GuidanceYear { get; set; }
        public Nullable<int> GuidanceMonth { get; set; }
        public Nullable<System.DateTime> GuidanceDate { get; set; }
        public Nullable<bool> HasExperssFees { get; set; }
        public Nullable<bool> HasInstallFees { get; set; }
        public Nullable<decimal> ExperssPrice { get; set; }
    }
}
