//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplementItem
    {
        public int SupplementId { get; set; }
        public Nullable<System.DateTime> BeginDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> SubjectId { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<System.DateTime> AddDate { get; set; }
        public Nullable<int> AddUserId { get; set; }
        public string Reason { get; set; }
        public string Remark { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<int> ApproveState { get; set; }
        public Nullable<System.DateTime> ApproveDate { get; set; }
        public Nullable<int> ApproveUserId { get; set; }
        public string ApproveRemark { get; set; }
        public Nullable<int> IsSubmit { get; set; }
    }
}
